package com.swift.heartbeat.constants;

public enum Constants {

	SENDER_BIC("SENDER_BIC"),
	RECEIVER_BIC("RECEIVER_BIC"),
	ELAPSED_TIME("ELAPSED_TIME"),
	SENDER_MON_START_TIME("SENDER_MON_START_TIME"),
	SENDER_MON_END_TIME("SENDER_MON_END_TIME"),
	SENDER_TUES_START_TIME("SENDER_TUES_START_TIME"),
	SENDER_TUES_END_TIME("SENDER_TUES_END_TIME"),
	SENDER_WED_START_TIME("SENDER_WED_START_TIME"),
	SENDER_WED_END_TIME("SENDER_WED_END_TIME"),
	SENDER_THUR_START_TIME("SENDER_THUR_START_TIME"),
	SENDER_THUR_END_TIME("SENDER_THUR_END_TIME"),
	SENDER_FRI_START_TIME("SENDER_FRI_START_TIME"),
	SENDER_FRI_END_TIME("SENDER_FRI_END_TIME"),
	SENDER_SAT_START_TIME("SENDER_SAT_START_TIME"),
	SENDER_SAT_END_TIME("SENDER_SAT_END_TIME"),
	SENDER_SUN_START_TIME("SENDER_SUN_START_TIME"),
	SENDER_SUN_END_TIME("SENDER_SUN_END_TIME"),
	ALARMIST_MON_START_TIME("ALARMIST_MON_START_TIME"),
	ALARMIST_MON_END_TIME("ALARMIST_MON_END_TIME"),
	ALARMIST_TUES_START_TIME("ALARMIST_TUES_START_TIME"),
	ALARMIST_TUES_END_TIME("ALARMIST_TUES_END_TIME"),
	ALARMIST_WED_START_TIME("ALARMIST_WED_START_TIME"),
	ALARMIST_WED_END_TIME("ALARMIST_WED_END_TIME"),
	ALARMIST_THUR_START_TIME("ALARMIST_THUR_START_TIME"),
	ALARMIST_THUR_END_TIME("ALARMIST_THUR_END_TIME"),
	ALARMIST_FRI_START_TIME("ALARMIST_FRI_START_TIME"),
	ALARMIST_FRI_END_TIME("ALARMIST_FRI_END_TIME"),
	ALARMIST_SAT_START_TIME("ALARMIST_SAT_START_TIME"),
	ALARMIST_SAT_END_TIME("ALARMIST_SAT_END_TIME"),
	ALARMIST_SUN_START_TIME("ALARMIST_SUN_START_TIME"),
	ALARMIST_SUN_END_TIME("ALARMIST_SUN_END_TIME"),
	NEW("NEW"),
	COMPLETED("COMPLETED"),
	SMTP_HOST("SMTP_HOST"),
	SMTP_PORT("SMTP_PORT"),
	SMTP_AUTH("SMTP_AUTH"),
	SMTP_STARTTLS_ENABLE("SMTP_STARTTLS_ENABLE"),
	SMTP_SENDER("SMTP_SENDER"),
	SMTP_SENDER_PASSWORD("SMTP_SENDER_PASSWORD"),
	RECIPIENT("RECIPIENT"),
	SUCCESS("SUCCESS"),
	FAILURE("FAILURE"),
	EMAIL_SUBJECT("EMAIL_SUBJECT"),
	EMAIL_BODY("EMAIL_BODY"), 
	HOUSEKEEPING_TERM_IN_DAYS("HOUSEKEEPING_TERM_IN_DAYS"),
	NO_RUN("NO_RUN"),
	REQ_QUEUE_NAME("REQ_QUEUE_NAME"),
	REP_QUEUE_NAME("REP_QUEUE_NAME"),
	TRUE("TRUE"),
	FALSE("FALSE");
	
	private String value;
	
	Constants(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}

}
